name: Deploy to EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./server
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/banner-app:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/banner-app:latest
          docker stop banner-app-container || true
          docker rm banner-app-container || true
          docker run -d --name banner-app-container \
            -p 3000:3000 \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -e PORT=${{ secrets.PORT }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e CLIENT_URL=${{ secrets.CLIENT_URL }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/banner-app:latest
          docker system prune -af